import { Inter as FontSans } from "next/font/google"
import './globals.css'
import ContextProvider from '@/contexts/contextProvider'
import { cn } from "@/lib/utils"
 
export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
		<ContextProvider>
     		<body className={cn(
          "font-sans antialiased",
          fontSans.variable
        )}>{children}</body>	
		</ContextProvider>
    </html>
  )
}
