
import { Inter as FontSans } from "next/font/google"
import './globals.css'
import ContextProvider from '@/providers/contextProvider'
import { cn } from "@/lib/utils"
import ThemeProvider from "@/providers/themeProvider"
import AuthSessionProvider from "@/providers/authSessionProvider"
import DefaultNavbar from "@/components/default-navbar"
 
export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, session }) {
  return (
    <html lang="en" suppressHydrationWarning>
     		<body className={cn(
          "dark text-foreground bg-background font-sans antialiased",
          fontSans.variable
        )}>
					<AuthSessionProvider>
					<ContextProvider>
						<ThemeProvider>
								{children}
						</ThemeProvider>
					</ContextProvider>
					</AuthSessionProvider>
				</body>	
    </html>
  )
}
