import { Inter } from 'next/font/google'
import './globals.css'
import ContextProvider from '@/contexts/contextProvider'
 
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
		<ContextProvider>
     		<body>{children}</body>	
		</ContextProvider>
    </html>
  )
}
